CREATE TABLE IF NOT EXISTS `as_admin_tag_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(128) DEFAULT NULL,
  `type_key` VARCHAR(128) DEFAULT NULL,
  `description` VARCHAR(512) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_type_key` (`type_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签类型表';

CREATE TABLE IF NOT EXISTS `as_admin_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(128) NOT NULL,
  `tag_key` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512) DEFAULT NULL,
  `color` VARCHAR(32) DEFAULT NULL,
  `tag_type_key` VARCHAR(128) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1,
  `usage_count` INT DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_key` (`tag_key`),
  KEY `idx_tag_type_key` (`tag_type_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签表';

CREATE TABLE IF NOT EXISTS `as_admin_plugin_table_permission_request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `table_name` VARCHAR(128) NOT NULL,
  `requested_operations` VARCHAR(255) DEFAULT NULL,
  `is_readonly` TINYINT(1) DEFAULT 0,
  `reason` VARCHAR(1000) DEFAULT NULL,
  `description` VARCHAR(1000) DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT 'PENDING',
  `applicant_id` VARCHAR(128) DEFAULT NULL,
  `applicant_name` VARCHAR(128) DEFAULT NULL,
  `reviewer_id` VARCHAR(128) DEFAULT NULL,
  `reviewer_name` VARCHAR(128) DEFAULT NULL,
  `review_comment` VARCHAR(1000) DEFAULT NULL,
  `review_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ptr_plugin_id` (`plugin_id`),
  KEY `idx_ptr_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件表权限申请表';

CREATE TABLE IF NOT EXISTS `as_admin_plugin_table_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `table_name` VARCHAR(128) NOT NULL,
  `allowed_operations` VARCHAR(255) DEFAULT NULL,
  `is_readonly` TINYINT(1) DEFAULT 0,
  `description` VARCHAR(1000) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` VARCHAR(128) DEFAULT NULL,
  `update_by` VARCHAR(128) DEFAULT NULL,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_table_name` (`plugin_id`,`table_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件表权限配置表';

CREATE TABLE IF NOT EXISTS `as_admin_review_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rule_name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1000) DEFAULT NULL,
  `rule_type` VARCHAR(64) DEFAULT NULL,
  `conditions` TEXT DEFAULT NULL,
  `actions` TEXT DEFAULT NULL,
  `priority` INT DEFAULT 0,
  `enabled` TINYINT(1) DEFAULT 1,
  `match_count` INT DEFAULT 0,
  `last_match_time` DATETIME DEFAULT NULL,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_rule_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审核规则表';

CREATE TABLE IF NOT EXISTS `as_admin_version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `version` VARCHAR(64) NOT NULL,
  `file_path` VARCHAR(512) DEFAULT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `file_hash` VARCHAR(128) DEFAULT NULL,
  `release_notes` TEXT DEFAULT NULL,
  `is_current` TINYINT(1) DEFAULT 0,
  `status` VARCHAR(32) DEFAULT NULL,
  `upload_time` DATETIME DEFAULT NULL,
  `dependencies` TEXT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_version` (`plugin_id`,`version`),
  KEY `idx_version_current` (`is_current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件版本表';

CREATE TABLE IF NOT EXISTS `as_admin_plugin_submission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `plugin_name` VARCHAR(255) DEFAULT NULL,
  `plugin_type` VARCHAR(64) DEFAULT NULL,
  `version` VARCHAR(64) NOT NULL,
  `developer_id` VARCHAR(128) DEFAULT NULL,
  `developer_name` VARCHAR(128) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `icon` VARCHAR(512) DEFAULT NULL,
  `tags` TEXT DEFAULT NULL,
  `category` VARCHAR(128) DEFAULT NULL,
  `file_path` VARCHAR(512) DEFAULT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `file_hash` VARCHAR(128) DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT 'PENDING',
  `reviewer_id` VARCHAR(128) DEFAULT NULL,
  `reviewer_name` VARCHAR(128) DEFAULT NULL,
  `review_time` DATETIME DEFAULT NULL,
  `review_comment` VARCHAR(1000) DEFAULT NULL,
  `scan_status` VARCHAR(32) DEFAULT NULL,
  `scan_result` TEXT DEFAULT NULL,
  `submit_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_submission_plugin_id` (`plugin_id`),
  KEY `idx_submission_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件提审表';

CREATE TABLE IF NOT EXISTS `as_admin_plugin_statistics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `stat_date` DATE NOT NULL,
  `install_count` INT DEFAULT 0,
  `uninstall_count` INT DEFAULT 0,
  `active_installs` INT DEFAULT 0,
  `active_users` INT DEFAULT 0,
  `new_users` INT DEFAULT 0,
  `rating_average` DECIMAL(10,2) DEFAULT 0.00,
  `rating_count` INT DEFAULT 0,
  `review_count` INT DEFAULT 0,
  `feedback_count` INT DEFAULT 0,
  `report_count` INT DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_stat_date` (`plugin_id`,`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件统计表';

CREATE TABLE IF NOT EXISTS `as_admin_plugin_review_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `submission_id` BIGINT NOT NULL,
  `plugin_id` VARCHAR(128) DEFAULT NULL,
  `version` VARCHAR(64) DEFAULT NULL,
  `reviewer_id` VARCHAR(128) DEFAULT NULL,
  `reviewer_name` VARCHAR(128) DEFAULT NULL,
  `decision` VARCHAR(32) DEFAULT NULL,
  `comment` VARCHAR(1000) DEFAULT NULL,
  `review_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_prh_submission_id` (`submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件审核历史表';

CREATE TABLE IF NOT EXISTS `as_admin_manager` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) NOT NULL,
  `plugin_name` VARCHAR(255) DEFAULT NULL,
  `plugin_type` VARCHAR(128) DEFAULT NULL,
  `current_version` VARCHAR(64) DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT NULL,
  `developer_id` VARCHAR(128) DEFAULT NULL,
  `developer_name` VARCHAR(128) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `icon` VARCHAR(512) DEFAULT NULL,
  `category` VARCHAR(128) DEFAULT NULL,
  `install_count` INT DEFAULT 0,
  `rating_average` DOUBLE DEFAULT 0,
  `delist_reason` VARCHAR(1000) DEFAULT NULL,
  `delist_time` DATETIME DEFAULT NULL,
  `tags` TEXT DEFAULT NULL,
  `price_type` VARCHAR(32) DEFAULT 'free',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_manager_plugin_id` (`plugin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件管理主表';

CREATE TABLE IF NOT EXISTS `as_admin_feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `plugin_id` VARCHAR(128) DEFAULT NULL,
  `plugin_version` VARCHAR(64) DEFAULT NULL,
  `feedback_type` VARCHAR(64) DEFAULT NULL,
  `title` VARCHAR(255) DEFAULT NULL,
  `content` TEXT DEFAULT NULL,
  `severity` VARCHAR(32) DEFAULT NULL,
  `user_id` VARCHAR(128) DEFAULT NULL,
  `username` VARCHAR(128) DEFAULT NULL,
  `contact` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT NULL,
  `handler_id` VARCHAR(128) DEFAULT NULL,
  `handler_name` VARCHAR(128) DEFAULT NULL,
  `handle_time` DATETIME DEFAULT NULL,
  `handle_comment` VARCHAR(1000) DEFAULT NULL,
  `attachments` TEXT DEFAULT NULL,
  `submit_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_plugin_id` (`plugin_id`),
  KEY `idx_feedback_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户反馈表';

CREATE TABLE IF NOT EXISTS `as_admin_display_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `config_key` VARCHAR(128) NOT NULL,
  `config_value` TEXT DEFAULT NULL,
  `description` VARCHAR(512) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_display_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='展示配置表';

CREATE TABLE IF NOT EXISTS `as_admin_developer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `username` VARCHAR(128) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `display_name` VARCHAR(128) DEFAULT NULL,
  `company` VARCHAR(255) DEFAULT NULL,
  `website` VARCHAR(512) DEFAULT NULL,
  `bio` TEXT DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT NULL,
  `verified` TINYINT(1) DEFAULT 0,
  `plugin_count` INT DEFAULT 0,
  `total_downloads` INT DEFAULT 0,
  `reviewer_id` VARCHAR(128) DEFAULT NULL,
  `review_time` DATETIME DEFAULT NULL,
  `review_comment` VARCHAR(1000) DEFAULT NULL,
  `apply_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_developer_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='开发者表';

CREATE TABLE IF NOT EXISTS `as_admin_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(128) NOT NULL,
  `category_key` VARCHAR(128) NOT NULL,
  `description` VARCHAR(512) DEFAULT NULL,
  `icon` VARCHAR(255) DEFAULT NULL,
  `display_order` INT DEFAULT 0,
  `enabled` TINYINT(1) DEFAULT 1,
  `plugin_count` INT DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_key` (`category_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分类表';

CREATE TABLE IF NOT EXISTS `as_admin_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `operation_type` VARCHAR(64) DEFAULT NULL,
  `operation_name` VARCHAR(255) DEFAULT NULL,
  `operation_desc` VARCHAR(1000) DEFAULT NULL,
  `target_type` VARCHAR(64) DEFAULT NULL,
  `target_id` VARCHAR(128) DEFAULT NULL,
  `target_name` VARCHAR(255) DEFAULT NULL,
  `operator_id` VARCHAR(128) DEFAULT NULL,
  `operator_name` VARCHAR(128) DEFAULT NULL,
  `operator_ip` VARCHAR(64) DEFAULT NULL,
  `result` VARCHAR(32) DEFAULT NULL,
  `error_message` VARCHAR(1000) DEFAULT NULL,
  `before_data` TEXT DEFAULT NULL,
  `after_data` TEXT DEFAULT NULL,
  `operation_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_target` (`target_type`,`target_id`),
  KEY `idx_audit_operator` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审计日志表';

CREATE TABLE IF NOT EXISTS `as_admin_signing_key` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key_id` VARCHAR(128) NOT NULL,
  `alias` VARCHAR(128) DEFAULT NULL,
  `keystore_url` VARCHAR(1024) DEFAULT NULL,
  `store_password_enc` TEXT DEFAULT NULL,
  `key_password_enc` TEXT DEFAULT NULL,
  `public_key_pem` TEXT DEFAULT NULL,
  `public_fingerprint_sha256` VARCHAR(128) DEFAULT NULL,
  `active` TINYINT(1) DEFAULT 0,
  `trusted_until` DATETIME DEFAULT NULL,
  `revoked_at` DATETIME DEFAULT NULL,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_signing_key_id` (`key_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签名密钥表';

CREATE TABLE IF NOT EXISTS `as_admin_download_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token_hash` VARCHAR(255) NOT NULL,
  `plugin_id` VARCHAR(128) NOT NULL,
  `version` VARCHAR(64) DEFAULT NULL,
  `key_id` VARCHAR(128) DEFAULT NULL,
  `user_id` VARCHAR(128) DEFAULT NULL,
  `issued_ip` VARCHAR(64) DEFAULT NULL,
  `issued_ua` VARCHAR(512) DEFAULT NULL,
  `expire_at` DATETIME NOT NULL,
  `used` TINYINT(1) DEFAULT 0,
  `used_at` DATETIME DEFAULT NULL,
  `consumed_ip` VARCHAR(64) DEFAULT NULL,
  `consumed_ua` VARCHAR(512) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_download_token_hash` (`token_hash`),
  KEY `idx_download_token_plugin` (`plugin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='下载令牌表';

CREATE TABLE IF NOT EXISTS `as_admin_api_nonce` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key_id` VARCHAR(128) NOT NULL,
  `nonce` VARCHAR(128) NOT NULL,
  `expire_at` DATETIME NOT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_nonce` (`key_id`,`nonce`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API防重放nonce表';

CREATE TABLE IF NOT EXISTS `as_admin_api_key` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `key_id` VARCHAR(128) NOT NULL,
  `secret_hash` VARCHAR(255) NOT NULL,
  `secret_enc` TEXT DEFAULT NULL,
  `scopes` TEXT DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1,
  `expire_at` DATETIME DEFAULT NULL,
  `last_used_at` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` VARCHAR(128) DEFAULT NULL,
  `updated_by` VARCHAR(128) DEFAULT NULL,
  `namespace_code` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_key_key_id` (`key_id`),
  KEY `idx_api_key_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API密钥表';
