plugin.id=appstore-admin
plugin.class=com.keqi.gress.plugin.appstore.admin.AppStoreAdminPlugin
plugin.version=1.0.11
plugin.provider=Gress Team
plugin.description=Plugin Store Management System - Provides plugin review, listing, delisting, version management and other management functions
plugin.license=MIT
plugin.requires=*
